### ISSUE TITLE
Make a better logo.

### ISSUE THREAD

**Issue by ghost** [ackOS-project/ackOS#2]
I know this is largely irreverent but my god, That logo looks really interesting (in a bad way). I mean I'm not **someone** to say this because My projects also have shitty looking logos but man that cat looks like it was run over by a bus. Man just tell me and I will make a logo for you if you want but god, take that cat to a hospital or something.

This was a over denaturation, I don't dislike the logo, but maybe it's time for a redesign. If it was made by you then don't take any offence, I can't make good logos either. PS. bye.

**Comment by ghost** [comment]
Maybe just commission someone on fiverr.

**Comment by eliasoberholtz** [comment]
I'll try to make something better but I can't make any promises that it will be GOOD. I'll try to help when I can.

**Comment by masterneko** [comment]
@ghost I see you have deleted your account, so I'm talking to the void now :(.

I appreciate your critique for it has inspired the creation of a new logo.

![cat](https://raw.githubusercontent.com/ackOS-project/ackOS/rewrite/assets/logos/logo.png)

Thank you :cat:
