### ISSUE TITLE
I cannot Build The tool chain 

### ISSUE THREAD

**Issue by Siddhesh2377** [ackOS-project/ackOS#4]
It Says './toolchain/build.sh: line 18: cd: too many arguments'

**Comment by masterneko** [comment]
I assume you have placed the source code on a path which contains whitespace (eg, `/home/User Name/ackOS`). The `cd` command in the script has recognised the path as command line arguments. As a quick fix, move the folder into a path without spaces.

**Comment by Siddhesh2377** [comment]
I will try again and i will update you ..

**Comment by Siddhesh2377** [comment]
see It Shows me this error --> 

cp: cannot stat 'config/dist/ackos-x86_64-limine/resources': No such file or directory
make: *** [config/dist/ackos-x86_64-limine/build.mk:10: bin/ackos-x86_64-limine.iso] Error 1

**Comment by masterneko** [comment]
Unfortunately, Git doesn't track empty folders by default. You need to create the directory manually.

**Comment by Siddhesh2377** [comment]
i have created but then also it shows this error

**Comment by masterneko** [comment]
> i have created but then also it shows this error

I can't see the error 🙃, can you please send it ツ
